message

diff --git a/.github/workflows/Continous_intergration.yml b/.github/workflows/Continous_intergration.yml
--- a/.github/workflows/Continous_intergration.yml
+++ b/.github/workflows/Continous_intergration.yml
@@ -63,15 +63,15 @@ jobs:
         with:
           java-version: 17
       
-      - name: Install Maven
-        run: |
-          if ! command -v mvn &> /dev/null; then
-            echo "Maven not found. Installing Maven..."
-            sudo apt update
-            sudo apt install -y maven
-          else
-            echo "Maven is already installed."
-          fi
+      # - name: Install Maven
+      #   run: |
+      #     if ! command -v mvn &> /dev/null; then
+      #       echo "Maven not found. Installing Maven..."
+      #       sudo apt update
+      #       sudo apt install -y maven
+      #     else
+      #       echo "Maven is already installed."
+      #     fi
 
       - name: Build and analyze
         env:
